---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true
  vars_files:
    - vault-pass.yml
  tasks:
  - name: clone a repo
    git:
      repo: https://anandcn009:{{ password }}/anandcn009/vault.git
      dest: /opt/ansadmin/test3-vault
