---
# tasks file for setup-apache
- name: install packages
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: start apache

- name: start apache2
  service:
   name: apache2
   state: started
  when: ansible_os_family == "Debian"

- name: copy index.html
  copy:
   src: /opt/ansible/index.html
   dest: /var/www/html
   mode: 0666

